### ISSUE TITLE
ServiceWorker fails to register in live demo

### ISSUE THREAD

**Issue by tgrandgent** [GoogleChromeLabs/so-pwa#2]
The live demo currently produces the following errors in the Chrome console:

```
VM24 workbox-cache-expiration.dev.js:521 Uncaught TypeError: quota_mjs.registerCallback is not a function
Plugin @ VM24 workbox-cache-expiration.dev.js:521
(anonymous) @ service-worker.js:63
(anonymous) @ service-worker.js:65
(index):1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker: ServiceWorker script evaluation failed
```

This appears to be caused by a [recent commit](https://github.com/GoogleChromeLabs/so-pwa/commit/17f5bae4be841265c2ff56980ec189cf4013492a) in which purgeOnQuotaError was set to true, causing this failing code path to become active.

**Comment by jeffposnick** [comment]
Oops—thanks for pointing that out!
